version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - storage:/app/storage
      - .:/rails
      - ruby-bundle-cache:/bundle
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    links:
      - pg
    command: bundle exec puma
    stdin_open: true
    tty: true
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis: 
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
     - ./tmp/redis_data:/var/lib/redis/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  storage: {}
  redis: {}
  ruby-bundle-cache: {}
